-- Importação do plantel atual (baias + aves adultas reprodutoras)
-- Gerado a partir da lista enviada pelo Gabriel em 23/09/2026.
-- Seguro rodar mais de uma vez: os códigos são fixos e o insert usa
-- ON CONFLICT (codigo) DO NOTHING, então rodar de novo não duplica nada.

-- ---------------------------------------------------------------------------
-- 1) Baias
-- ---------------------------------------------------------------------------
insert into public.baias (codigo, numero, nome, especie, status, destino_padrao)
values
  ('B001', '1', 'Baia 1 — Angola Lavanda', 'Angola Lavanda', 'Reprodução', 'venda'),
  ('B002', '2', 'Baia 2 — Angola Preta', 'Angola Preta', 'Reprodução', 'venda'),
  ('B003', '3', 'Baia 3 — Angola Canela', 'Angola Canela', 'Reprodução', 'venda'),
  ('B004', '4', 'Baia 4 — Angola Branca', 'Angola Branca', 'Reprodução', 'venda'),
  ('B005', '5', 'Baia 5 — Angola Branca', 'Angola Branca', 'Reprodução', 'venda'),
  ('B006', '6', 'Baia 6 — Faisão Coleira', 'Faisão Coleira', 'Reprodução', 'venda'),
  ('B007', '7', 'Baia 7 — Faisão Versicolor', 'Faisão Versicolor', 'Reprodução', 'venda'),
  ('B008', '8', 'Baia 8 — Faisão Prateado', 'Faisão Prateado', 'Reprodução', 'venda'),
  ('B009', '9', 'Baia 9 — GSB Baia 2', 'GSB Baia 2', 'Reprodução', 'venda'),
  ('B010', '10', 'Baia 10 — GSB Baia 1', 'GSB Baia 1', 'Reprodução', 'venda'),
  ('B011', '11', 'Baia 11 — Serama', 'Serama', 'Reprodução', 'venda'),
  ('B012', '12', 'Baia 12 — Belgiam', 'Belgiam', 'Reprodução', 'venda'),
  ('B013', '13', 'Baia 13 — Rodia Gigante', 'Rodia Gigante', 'Reprodução', 'venda'),
  ('B014', '14', 'Baia 14 — Mini Cochim Lavanda', 'Mini Cochim Lavanda', 'Reprodução', 'venda'),
  ('B015', '15', 'Baia 15 — Mini Cochim Preto', 'Mini Cochim Preto', 'Reprodução', 'venda'),
  ('B016', '16', 'Baia 16 — Vazia', 'Vazia', 'Inativa', 'venda'),
  ('B017', '17', 'Baia 17 — Polonesa', 'Polonesa', 'Reprodução', 'venda'),
  ('B018', '18', 'Baia 18 — Cara de Palhaço', 'Cara de Palhaço', 'Reprodução', 'venda'),
  ('B019', '19', 'Baia 19 — Sedosa', 'Sedosa', 'Reprodução', 'venda'),
  ('B020', '20', 'Baia 20 — Brahma White', 'Brahma White', 'Reprodução', 'venda'),
  ('B021', '21', 'Baia 21 — Brahma Lemom Pyle', 'Brahma Lemom Pyle', 'Reprodução', 'venda'),
  ('B022', '22', 'Baia 22 — Brahma Splash', 'Brahma Splash', 'Reprodução', 'venda'),
  ('B023', '23', 'Baia 23 — Ayam Cemani', 'Ayam Cemani', 'Reprodução', 'venda'),
  ('B024', '24', 'Baia 24 — Marreco Pompom Branco', 'Marreco Pompom Branco', 'Reprodução', 'venda'),
  ('B025', '25', 'Baia 25 — Marreco Pompom Colorido', 'Marreco Pompom Colorido', 'Reprodução', 'venda'),
  ('B026', '26', 'Baia 26 — Pavão Azul Indiano', 'Pavão Azul Indiano', 'Reprodução', 'venda'),
  ('B027', '27', 'Baia 27 — Pavão Azul Indiano', 'Pavão Azul Indiano', 'Reprodução', 'venda'),
  ('B028', '28', 'Baia 28 — Adultos a Venda', 'Adultos a Venda', 'Inativa', 'venda'),
  ('B029', '29', 'Baia 29 — Baia do Canto', 'Baia do Canto', 'Inativa', 'venda'),
  ('B030', '30', 'Baia 30 — Baia Chão Barracão', 'Baia Chão Barracão', 'Inativa', 'venda'),
  ('B031', '1A', 'Baia 1A — Baia aérea (Filhotada)', 'Baia aérea (Filhotada)', 'Inativa', 'venda'),
  ('B032', '2A', 'Baia 2A — Baia aérea (Filhotada)', 'Baia aérea (Filhotada)', 'Inativa', 'venda'),
  ('B033', '3A', 'Baia 3A — Baia aérea (Filhotada)', 'Baia aérea (Filhotada)', 'Inativa', 'venda'),
  ('B034', '4A', 'Baia 4A — Baia aérea (Filhotada)', 'Baia aérea (Filhotada)', 'Inativa', 'venda')
on conflict (codigo) do nothing;

-- ---------------------------------------------------------------------------
-- 2) Aves adultas reprodutoras (uma linha por ave individual)
-- ---------------------------------------------------------------------------
insert into public.aves (codigo, baia_id, nome, emoji, sexo, status)
values
  ('AVE-IMP-0001', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0002', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0003', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0004', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0005', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0006', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0007', (select id from public.baias where codigo = 'B001'), 'Angola Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0008', (select id from public.baias where codigo = 'B002'), 'Angola Preta', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0009', (select id from public.baias where codigo = 'B002'), 'Angola Preta', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0010', (select id from public.baias where codigo = 'B002'), 'Angola Preta', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0011', (select id from public.baias where codigo = 'B003'), 'Angola Canela', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0012', (select id from public.baias where codigo = 'B003'), 'Angola Canela', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0013', (select id from public.baias where codigo = 'B003'), 'Angola Canela', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0014', (select id from public.baias where codigo = 'B003'), 'Angola Canela', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0015', (select id from public.baias where codigo = 'B003'), 'Angola Canela', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0016', (select id from public.baias where codigo = 'B004'), 'Angola Branca', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0017', (select id from public.baias where codigo = 'B004'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0018', (select id from public.baias where codigo = 'B004'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0019', (select id from public.baias where codigo = 'B004'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0020', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0021', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0022', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0023', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0024', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0025', (select id from public.baias where codigo = 'B005'), 'Angola Branca', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0026', (select id from public.baias where codigo = 'B006'), 'Faisão Coleira', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0027', (select id from public.baias where codigo = 'B006'), 'Faisão Coleira', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0028', (select id from public.baias where codigo = 'B006'), 'Faisão Coleira', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0029', (select id from public.baias where codigo = 'B006'), 'Faisão Coleira', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0030', (select id from public.baias where codigo = 'B006'), 'Faisão Coleira', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0031', (select id from public.baias where codigo = 'B007'), 'Faisão Versicolor', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0032', (select id from public.baias where codigo = 'B007'), 'Faisão Versicolor', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0033', (select id from public.baias where codigo = 'B007'), 'Faisão Versicolor', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0034', (select id from public.baias where codigo = 'B008'), 'Faisão Prateado', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0035', (select id from public.baias where codigo = 'B008'), 'Faisão Prateado', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0036', (select id from public.baias where codigo = 'B008'), 'Faisão Prateado', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0037', (select id from public.baias where codigo = 'B009'), 'GSB Baia 2', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0038', (select id from public.baias where codigo = 'B009'), 'GSB Baia 2', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0039', (select id from public.baias where codigo = 'B009'), 'GSB Baia 2', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0040', (select id from public.baias where codigo = 'B009'), 'GSB Baia 2', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0041', (select id from public.baias where codigo = 'B009'), 'GSB Baia 2', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0042', (select id from public.baias where codigo = 'B010'), 'GSB Baia 1', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0043', (select id from public.baias where codigo = 'B010'), 'GSB Baia 1', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0044', (select id from public.baias where codigo = 'B010'), 'GSB Baia 1', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0045', (select id from public.baias where codigo = 'B010'), 'GSB Baia 1', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0046', (select id from public.baias where codigo = 'B010'), 'GSB Baia 1', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0047', (select id from public.baias where codigo = 'B011'), 'Serama', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0048', (select id from public.baias where codigo = 'B011'), 'Serama', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0049', (select id from public.baias where codigo = 'B011'), 'Serama', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0050', (select id from public.baias where codigo = 'B011'), 'Serama', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0051', (select id from public.baias where codigo = 'B011'), 'Serama', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0052', (select id from public.baias where codigo = 'B012'), 'Belgiam', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0053', (select id from public.baias where codigo = 'B012'), 'Belgiam', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0054', (select id from public.baias where codigo = 'B012'), 'Belgiam', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0055', (select id from public.baias where codigo = 'B012'), 'Belgiam', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0056', (select id from public.baias where codigo = 'B012'), 'Belgiam', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0057', (select id from public.baias where codigo = 'B013'), 'Rodia Gigante', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0058', (select id from public.baias where codigo = 'B013'), 'Rodia Gigante', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0059', (select id from public.baias where codigo = 'B013'), 'Rodia Gigante', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0060', (select id from public.baias where codigo = 'B013'), 'Rodia Gigante', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0061', (select id from public.baias where codigo = 'B014'), 'Mini Cochim Lavanda', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0062', (select id from public.baias where codigo = 'B014'), 'Mini Cochim Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0063', (select id from public.baias where codigo = 'B014'), 'Mini Cochim Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0064', (select id from public.baias where codigo = 'B014'), 'Mini Cochim Lavanda', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0065', (select id from public.baias where codigo = 'B015'), 'Mini Cochim Preto', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0066', (select id from public.baias where codigo = 'B015'), 'Mini Cochim Preto', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0067', (select id from public.baias where codigo = 'B015'), 'Mini Cochim Preto', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0068', (select id from public.baias where codigo = 'B015'), 'Mini Cochim Preto', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0069', (select id from public.baias where codigo = 'B017'), 'Polonesa', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0070', (select id from public.baias where codigo = 'B017'), 'Polonesa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0071', (select id from public.baias where codigo = 'B017'), 'Polonesa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0072', (select id from public.baias where codigo = 'B017'), 'Polonesa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0073', (select id from public.baias where codigo = 'B017'), 'Polonesa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0074', (select id from public.baias where codigo = 'B018'), 'Cara de Palhaço', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0075', (select id from public.baias where codigo = 'B018'), 'Cara de Palhaço', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0076', (select id from public.baias where codigo = 'B018'), 'Cara de Palhaço', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0077', (select id from public.baias where codigo = 'B018'), 'Cara de Palhaço', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0078', (select id from public.baias where codigo = 'B018'), 'Cara de Palhaço', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0079', (select id from public.baias where codigo = 'B019'), 'Sedosa', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0080', (select id from public.baias where codigo = 'B019'), 'Sedosa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0081', (select id from public.baias where codigo = 'B019'), 'Sedosa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0082', (select id from public.baias where codigo = 'B019'), 'Sedosa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0083', (select id from public.baias where codigo = 'B019'), 'Sedosa', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0084', (select id from public.baias where codigo = 'B020'), 'Brahma White', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0085', (select id from public.baias where codigo = 'B020'), 'Brahma White', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0086', (select id from public.baias where codigo = 'B020'), 'Brahma White', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0087', (select id from public.baias where codigo = 'B020'), 'Brahma White', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0088', (select id from public.baias where codigo = 'B021'), 'Brahma Lemom Pyle', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0089', (select id from public.baias where codigo = 'B021'), 'Brahma Lemom Pyle', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0090', (select id from public.baias where codigo = 'B021'), 'Brahma Lemom Pyle', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0091', (select id from public.baias where codigo = 'B022'), 'Brahma Splash', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0092', (select id from public.baias where codigo = 'B022'), 'Brahma Splash', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0093', (select id from public.baias where codigo = 'B022'), 'Brahma Splash', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0094', (select id from public.baias where codigo = 'B023'), 'Ayam Cemani', '🐓', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0095', (select id from public.baias where codigo = 'B023'), 'Ayam Cemani', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0096', (select id from public.baias where codigo = 'B023'), 'Ayam Cemani', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0097', (select id from public.baias where codigo = 'B023'), 'Ayam Cemani', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0098', (select id from public.baias where codigo = 'B023'), 'Ayam Cemani', '🐓', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0099', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0100', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0101', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0102', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0103', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0104', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0105', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0106', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0107', (select id from public.baias where codigo = 'B024'), 'Marreco Pompom Branco', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0108', (select id from public.baias where codigo = 'B025'), 'Marreco Pompom Colorido', '🦆', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0109', (select id from public.baias where codigo = 'B025'), 'Marreco Pompom Colorido', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0110', (select id from public.baias where codigo = 'B025'), 'Marreco Pompom Colorido', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0111', (select id from public.baias where codigo = 'B025'), 'Marreco Pompom Colorido', '🦆', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0112', (select id from public.baias where codigo = 'B026'), 'Pavão Azul Indiano', '🦚', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0113', (select id from public.baias where codigo = 'B026'), 'Pavão Azul Indiano', '🦚', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0114', (select id from public.baias where codigo = 'B026'), 'Pavão Azul Indiano', '🦚', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0115', (select id from public.baias where codigo = 'B026'), 'Pavão Azul Indiano', '🦚', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0116', (select id from public.baias where codigo = 'B027'), 'Pavão Azul Indiano', '🦚', 'Macho', 'Macho reprodutor'),
  ('AVE-IMP-0117', (select id from public.baias where codigo = 'B027'), 'Pavão Azul Indiano', '🦚', 'Fêmea', 'Fêmea reprodutora'),
  ('AVE-IMP-0118', (select id from public.baias where codigo = 'B027'), 'Pavão Azul Indiano', '🦚', 'Fêmea', 'Fêmea reprodutora')
on conflict (codigo) do nothing;

